server:
  port: 8080
spring:
  data:
    mongodb:
      uri: mongodb+srv://millisrivastava73_db_user:<db_password>@cluster0.oug6802.mongodb.net/?appName=Cluster0
jwt:
  secret: VerySecretKeyChangeThisInProd1234567890
  expiration-ms: 86400000
